### ISSUE TITLE
Unrelevant error message when no user in database

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#244]
When I try to connect to an new installation of PaSSHport, with no user, I have the following message : 
```
[>] ssh passhport@bastion.librit.fr
No user exists in database or can't reach passhportd.
tip: it can be a SSL certificate misconfiguration.
Connection to bastion.librit.fr closed.
```
I think we should delete carefully test if this is really an SSL problem, or the fact that they is actually no user.

**Comment by elg** [comment]
Can you provide how you obtain this message? what command is passed / what user... 

This message appears when the passhport script tries to get targets accessibles by a user, whatever the problem is. Apparently the common issues are SSL conf or database users but it can be a lot of other issues (network, disk access...). If we want to separate the user in database issue, I need the exact pattern and test it before (which is not always a good idea but I need to see to choose).

Maybe a simple "Error getting accessible targets" will be better cause at least it don't leads to wrong issues.

**Comment by Raphux** [comment]
Can't reproduce anymore… 

Sorry for the noise.
