### ISSUE TITLE
The use of proxyjump option bypass passhport

### ISSUE THREAD

**Issue by florian-mole** [LibrIT/passhport#364]
Hello,

 I'm interested in your product but i noticed what might be an issue.

Let's say i have a passhport bastion : pbastion
and two servers : server1, server2

In passhport configuration i have a user : user1
user1 has his public key on both server1 and server2 and of course on pbastion
I gave user1 access only to the target server1 on pbastion

However If i use the option proxyjump on my client, i can also reach server2 without any authorization given in passhport config :

ssh -oProxyJump=passhport@pbastion user1@server2

This is an issue because any of my users would be able to bypass passhport config simply by using a single proxyjump client-side configuration.

On the other hand, ProxyJump seems to be a very usefull functionnality.
It's the only way i found to for proxying winscp.  
I'm under the impression the project does not provide any related documentation for now.

I hope you will be able to help me.

Anyway thanks for your work on this product.

**Comment by elg** [comment]
Hello,

Sorry for the late answer and tank you for the bug report. I can reproduce this behavior only if I have my local pubkey on server2.
Can you confirm that is your configuration (and I'm not sure we can deal with that... but we are checking).

For winscp, short answer: we did work for the scp command line on Linux only. The syntax for scp is something like:
scp localfile passhport@pbastion:server2//path/to/copy/ 
Maybe winscp allow you a command line interface to have a similar command line. I'll check out that too.

And finaly: thanks for giving a shot on passhport ;)

**Comment by elg** [comment]
Ok first check: it's possible to deactivate this behavior you can add this in your passhport sshd config:

AllowTcpForwarding no

Warning: doing that you disable the port forwarding capabilities of passhport sshd server... It can be an issue. Today we suggest to let "AllowTcpForwarding" to "yes" and to monitor your server authorizedkeys if it is an issue.

I remove the "bug" tag since it is a configuration choice... And I check for winscp later.

**Comment by florian-mole** [comment]
Hello,

Thank you for your answer.

> Sorry for the late answer and tank you for the bug report. I can reproduce this behavior only if I have my local pubkey on server2.

Yes, my public key is on server2. 
If the user does not have his key or an account on the server the access is denied.

This was only bugging me because i did not expected passhport to let a user initiate an ssh connection to a server who is not in his target list.

I might have different types of users from students to external companies.
For me, allowing students to access the ssh port (even if the server denies access) of any other server accessed by passhport seems not optimal in matter of security.
However if i really want to separate my users i can still create differents passhport servers by security clearancer. 
It would just feels like i'm loosing the strenght of passhport for managing user access.

> Ok first check: it's possible to deactivate this behavior. To do it, you can add this in your passhport sshd config:
>
> AllowTcpForwarding no

Disabling the functionnality on the server, like you suggested, might be a solution in my case.

> For winscp, short answer: we did work for the scp command line on Linux only. The syntax for scp is something like:
scp localfile passhport@pbastion:server2//path/to/copy/
Maybe winscp allow you a command line interface to have a similar command line. I'll check out that too.

From a debian client i tried
scp test passhport@pbastion:server1//~

But i get the following error
lost connection

it seems passhport tries to connect with a password instead of a key

On server1 in /var/log/auth.log i get the following message
Jan 23 11:27:34 server1 sshd[28759]: Failed password for user1 from xxx.xxx.xxx.xxx port 48302 ssh2

If i add the option "-o ForwardAgent=yes" in the "SSH options:" of the target (passhport configuration) i have the same behaviour.

If you have any idea of what might be causing this, it would be really helpful.

Thanks a lot for your time.

**Comment by elg** [comment]
I understand your concern about letting a closed path accessible.
The solution of AllowTcpForwarding seems the best in your case.
Actually, after more tests, I figured out that "AllowTcpForwarding remote" seems a less blocking solution: it forbid only jumps from the client through passhport.


Anyway, if we don't solve your scp issue, the previous solution sounds useless... :)
Sadly I can't reproduce this issue. Are you sure that the bastion passhport ssh public key is in the server1 authorizedkeys? If the key is present, on the pbastion: 

1. As passhport user, check the passhport-admin target show server1.
2. As passhport user, try to ssh -v on server1 using the user/port/options from the previous result

If you see an issue connecting... you have to solve it (or paste me the output). if it connects well using the sshkey... I will need a scp -v to understand.
If we don't see anything on this, we found a complex bug that I'll be happy to be able to reproduce.

The ForwardAgent option should not impact anything of this connection. 

I still have to find a way on windows but you have to make it work on Linux first I think.

**Comment by florian-mole** [comment]
Hello,

Sorry for the delay, i did not have time to investigate the end of last week.

I did as you asked
1 - passhport-admin target show server1

```
Name: server1
Hostname: server1
Target type : ssh
Login: user
Port: 22
SSH options: 
Change password: False
Comment: 
Attached users: user
Usergroup list: 
Users who can access this target: user
All usergroups: 
Member of the following targetgroups:
```

2 - as passhport on pbastion 
To do this I connect with my admin account on passhport, then i use "sudo su - passhport" to change user)
If i try to connect to server1 (ssh -v user@server1) it asks me for a password.
This might be the normal behaviour seeing that i usurp passhport with "su - passhport".
Do you want the result of the command anyway ?

To investigate further i tried bypassing passhport by editing /home/passhport.ssh/authorized_keys
I removed the whole part before ssh-rsa
i.e. : command="/home/passhport/passhport-run-env/bin/python3 /home/passhport/passhport/passhport/passhport user"
Then
  - i log on passhport (ssh passhport@pbastion)
  - i log from pbastion to the target (ssh user@server1)
I was able to log on server1 with my ssh key. In this case it connects with my key and does not ask for a password.

Can we conclude from this test that there is no issue in the ssh configuration?

Thank you

**Comment by elg** [comment]
If I understand well, you're not using passhport in the right way.

You have genereate a ssh key on the pbastion as passhport user. Then you have to ssh-copy-id this key on the server1 (ssh-copy-id user@server1).

You need to restore the line on /home/passhport/.ssh/authorized_keys on pbastion if you have deleted it.

Now from your local computer you have to do:

`ssh passhport@pbastion`

Since you have register your key on passhport when you have created the user (passhport-admin user create) => you'll be connected on pbastion without password. 

However, you don't have access to a shell script, you're in a menu showing you what servers you can access. Since you've add the user on the server1 (passhport-admin target adduser user server1), the server1 is listed and you can select it.

Then passhport will try to connect to server1 using ssh user@server1
Since we've put the key before (with the ssh-copy-id) there is no password asked.

The key of the initial user is used only to connect to passhport. Then only the passhport sshkey is used to connect to the different targets.

I hope it is clear and I didn't missed your previous explanation. If I missed something, let me know, if something is not clear either and in best case: let me know if it's now working ;)

**Comment by florian-mole** [comment]
OK, thank you for the explanation.

I modified my configuration as you explained.
It works.

I am able to use ssh to connect to the server and scp works as well.

Winscp didn't work. I'll check if i can find a way for windows users to use scp with passhport.

**Comment by elg** [comment]
I'll create a new issue to address the scp on windows. I have no solution in mind right now.
