### ISSUE TITLE
Colors for hosts list ?

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#401]
Hi,

would there be an easy way to set color per host on the CLI when the host list is prompted (if the console permits it ) ?

**Comment by elg** [comment]
https://pypi.org/project/colored/ seems nice to do that

We need to enable/disable via configuration and to check the terminal capabilities before using it.
Key is to keep same color for the target every time we launch passhport.

**Comment by Raphux** [comment]
Would it be possible to set a specific color per host or hostgroup ?
For example, in my host list, I have different environments (dev/preprod/prod), and it would be great to set a color for all targets in dev scope, then another color for all targets in preprod scope, etc.

**Comment by elg** [comment]
So we would have to stick the colors to the targetgroups instead of targetnames.
Problem is a target can be part of multiple groups... I don't see an output here. Except taking an arbitrary rule to define the "color" targetgroup (eg: alphabetic).
Another way is to define a color from all the names of the targetgroups. For example: prod+secu=>orange, stag+secu=>pink, stag+secu+databas=>gray...
But it means a target will change his color if we add it to a targetgroups or remove from one...
