### ISSUE TITLE
Hosts list disapeared

### ISSUE THREAD

**Issue by nathonline** [LibrIT/passhport#410]
Hello everybody,

We are using PasshPort and previously every users was able to see the list of hosts and the select the good one. Now I am the only one able to see this list. 

Do you have an idea why ? Do we modified settings by mistake ? 

Thanks for your help guys !

**Comment by elg** [comment]
Hello,

That is a problem indeed! This can either be a bug or a configuration mistake. Since you can see the list, It is more probably a configuration mistake.

The list is built depending on the access you have. It means that if your user is not attached to a target, if he is not in a targetgroup that contains at least one target or in a usergroup that contains a target, he will not be able to see any host.

To check it, try to add the user directly to a target:
passhport-admin target adduser username targetname

After that you can check his connection by typing something like:
/home/passhport/passhport-run-env/bin/python3 /home/passhport/passhport/passhport/passhport alex@company.tld
(replacing alex@company.tld by the username). It will simulate the user connection.

If it still can't see it, you should have a stacktrace in the logs, you can check it in /var/log/apache2/error.log if you are using wsig (which is almost mandatory). If you give me the stack, I'll certainly be able to help you.

If you suspect another issue, do not hesitate to give me details.
