### ISSUE TITLE
How does Passhport intercept ssh connection and which script is launch at startup

### ISSUE THREAD

**Issue by Aguay-val** [LibrIT/passhport#551]
I was wondering how does passhport capture the ssh "new" connection and forward it to passhportd.
I thought it was a "bash script" at startup with .profile or something like this but no clue.

Can you help me understand ?

Thanks !

**Comment by elg** [comment]
Hi,

It's a openssh feature. Everything is set in the .authorized_keys file. If a line starts with a command, this command will be executed instead of a standard shell.

To understand: connect to your passhportd server and check /home/passhport/.ssh/authorized_keys file. It contains one line by user (by ssh public key) with a command to launch the script "passhport".

Is that clear?
